# ==============================================================================
# Copyright (C) 2018-2026 Intel Corporation
#
# SPDX-License-Identifier: MIT
# ==============================================================================

set (TARGET_NAME "gstvideoanalytics")

find_package(PkgConfig REQUIRED)
pkg_check_modules(GSTREAMER gstreamer-1.0>=1.16 REQUIRED)

add_library(${TARGET_NAME} SHARED register_elements.cpp)
set_compile_flags(${TARGET_NAME})
if(WIN32)
    add_vs_version_resource(${TARGET_NAME})
endif()

if(ENABLE_GENAI)
    target_compile_definitions(${TARGET_NAME} PRIVATE ENABLE_GENAI)
endif()

if(TARGET gvatrack)
    target_compile_definitions(${TARGET_NAME} PRIVATE ENABLE_GVATRACK)
endif()

if(TARGET audio_inference_elements)
    target_compile_definitions(${TARGET_NAME} PRIVATE ENABLE_AUDIO_INFERENCE_ELEMENTS_BUILT)
endif()

if(UNIX)
    target_compile_options(${TARGET_NAME} PRIVATE -Wno-error=unused-variable -Wno-error=unused-parameter)
endif()

target_include_directories(${TARGET_NAME}
PRIVATE
    ${GSTREAMER_INCLUDE_DIRS}
    ${CMAKE_CURRENT_SOURCE_DIR}
    ${CMAKE_CURRENT_SOURCE_DIR}/../elements/gvagenai/
    ${CMAKE_CURRENT_SOURCE_DIR}/../elements/gvametaaggregate/
    ${CMAKE_CURRENT_SOURCE_DIR}/../elements/gvametaconvert/
    ${CMAKE_CURRENT_SOURCE_DIR}/../elements/gvametapublish/
    ${CMAKE_CURRENT_SOURCE_DIR}/../elements/gvametapublish/base/
    ${CMAKE_CURRENT_SOURCE_DIR}/../elements/gvametapublish/file/
    ${CMAKE_CURRENT_SOURCE_DIR}/../elements/gvawatermark/
    ${CMAKE_CURRENT_SOURCE_DIR}/../elements/gvawatermark3d/
    ${CMAKE_CURRENT_SOURCE_DIR}/../elements/gvadeskew/
    ${CMAKE_CURRENT_SOURCE_DIR}/../elements/gvafpsthrottle/
    ${CMAKE_SOURCE_DIR}/include/dlstreamer/gst/metadata
)

if(TARGET gvatrack)
    target_include_directories(${TARGET_NAME} PRIVATE ${CMAKE_CURRENT_SOURCE_DIR}/../elements/gvatrack/)
endif()

target_link_libraries(${TARGET_NAME}
PRIVATE
    ${GSTREAMER_LIBRARIES}
    common
    elements
    inference_elements
    gvametapublish
)

if(TARGET gstdlstreamer_bins)
    target_link_libraries(${TARGET_NAME} PRIVATE gstdlstreamer_bins)
endif()

if(TARGET audio_inference_elements)
    target_link_libraries(${TARGET_NAME} PRIVATE audio_inference_elements)
endif()

if(TARGET gvatrack)
    target_link_libraries(${TARGET_NAME} PRIVATE gvatrack)
endif()

if(ENABLE_GENAI)
    target_link_libraries(${TARGET_NAME} PRIVATE gvagenai)
endif()

if(ENABLE_RISCV AND TARGET viplite_umd)
    target_link_libraries(${TARGET_NAME} PRIVATE viplite_umd)
endif()

install(TARGETS ${TARGET_NAME} DESTINATION ${DLSTREAMER_PLUGINS_INSTALL_PATH})
